[!5][BUG] When NaN is present inplace update can raise a RuntimeError
# Why is the change needed?

When audio chunks are 40 ms long, the inplace operation that replaces `NaN` with zeros currently fails with the following `RuntimeError`:

```
RuntimeError: Inplace update to inference tensor outside InferenceMode is not allowed.You can make a clone to get a normal tensor before doing inplace update.See https://github.com/pytorch/rfcs/pull/17 for more details.
```

For more information regarding the torch inference mode, refer to [the Torch guide](https://pytorch.org/docs/stable/generated/torch.inference_mode.html).

# What changes does the patch introduce?

Uses inference mode when performing all operations on tensors.

# How was this patch tested?

Manual execution on a problematic SRT, UTs already exist but do not cover tensors coming from the Sonar encoder.